[tox]
envlist = py310,py311,py312,py313
[testenv]
deps=pytest
commands=pytest

[pytest]
testpaths = test_irsx.py
norecursedirs = .git .tox .venv env build dist parsed xml test_data metadata irs_reader
